# This is a basic workflow to help you get started with Actions

name: BuildGCC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildgcc"
  buildgcc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo START

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          nproc
          sudo apt update -y
          sudo apt install build-essential make libmpc-dev libtool clang autotools-dev automake pkg-config bsdmainutils python3 libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler git libsqlite3-dev ccache
          mkdir /home/runner/work/gccbuild
          cd /home/runner/work/gccbuild
          CXX=clang++ CC=clang /home/runner/work/gcc/gcc/configure --host=x86_64-linux-gnu --enable-languages=c,c++ --prefix /home/runner/work/gccbuild --disable-multilib
          make -j 4
          # make clean
          # /home/runner/work/gcc/gcc/configure --host=x86_64-linux-gnu --prefix /home/runner/work/gccbuild --disable-multilib
          # make -j 8
          
  
